baseURL: "https://arkalim.org"
languageCode: en-us
title: Tony Gutierez
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: blog
      name: Blog
      url: /blog
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects
      weight: 30

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Tony Gutierrez"
    subtitle: Hello! I’m Tony, an **MBA** and **MIS** student at the University of Arizona. I bring a solid foundation in data analytics and project management, built by years of academic and professional experience. I am passionate about the entire data analysis process, from tidying dirty and unorganized data, to applying statistical analysis and data mining techniques, to building compelling data visualizations that help clients understand the meaning behind their data.  To enhance my expertise, I obtained the Google Data Analytics Professional Certificate, further bolstering my Excel, SQL, R Programming Language, and Tableau skills.  Moreover, I self-learned Python to consolidate my knowledge and to pursue my curiosity.  In my free time, I like to channel my creativity by learning new things, such as gardening and carpentry.
    imageUrl: "home/Short_Photo.jpg"
    imageWidth: 220
    imageHeight: 220
    # buttons:
    #   - name: Resume
    #     url: ""

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:tonygutierrez@arizona.edu"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/eangutierrez/"
    - name: "github"
      url: "https://github.com/eangutierrez"
    - name: "tableau public"
      url: "https://public.tableau.com/app/profile/tony.gutierrez"
    - name: "medium"
      url: "https://medium.com/@tonygutierrez_60520"
    - name: "cv"
      url: "https://drive.google.com/file/d/1CyiCqVQzENHBnYNQSgfMOuE7KursQ9qb/view?usp=drive_link"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
